config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists 
  resources :genres
  resources :songs
  
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
    has_many :genres, through: :songs

    def appos
        if self.name.last == "s"
            return self.name + "'"
        else 
            return self.name + "'s"
        end
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :artist
    belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    before_action :find_artist, only: [:show,:edit, :update, :destroy]
     
    def index
        @artists = Artist.all 

    end
    
    
    def show
        # @artist = Artist.find(params[:id])
    end
    
    
    
    def new
        @artist = Artist.new

    end

    def create 
    @artist = Artist.create(artist_params)
    redirect_to @artist
    end

    def edit
        #find_artist
    end

    def update
        @artist.update(artist_params)
        redirect_to @artist
    end

    def destroy
        
        @artist.destroy

        redirect_to artists_path
    end
    
    
    private 
    def artist_params
        params.require(:artist).permit(:name, :bio)
        end
    def find_artist
        @artist = Artist.find(params[:id])
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

def index
    @genres = Genre.all
end



end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :find_song , only: [:show, :edit, :update, :destroy]


    def index
        @songs = Song.all
    end

    def show

    end


    def new 
        @song = Song.new
    end

    def create 
        # byebug
     @song = Song.create(song_params)
     redirect_to @song.artist

    end


    private

    def song_params
        params.require(:song).permit(:artist_id, :genre_id, :name)
    end

    def find_song
        @song = Song.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h2>Edit 
<% if @artist.name.last == "s"  %> 
<%= @artist.name %>' 
<% else %> 
<%= @artist.name %>'s 
<% end %> 
Information Here</h2>

<%= form_for(@artist) do |f| %>
    <%= f.label :name %> :
    <%= f.text_field :name %>
    <%= f.label :bio %> :
    <%= f.text_field :bio %>
    <%= f.submit "Update #{@artist.name}'s info" %>
<% end %>
  

app/views/artists/index.html.erb
<h1>Welcome to Beats By Rails</h1>
<br>
<h3>Welcome to the Artist Home Page!</h3>

<% @artists.each do |a| %>
    <li>
    <%= link_to a.name, artist_path(a.id) %>
    </li>
<% end %>

app/views/artists/new.html.erb
<h5>List a New Artist Here!</h5>

<%= form_for(@artist) do |f| %>
    <%= f.label :name %> :
    <%= f.text_field :name %>
    <%= f.label :bio %>
    <%= f.text_field :bio %>
    <%= f.submit "Add Artist" %>
<% end %>
  

app/views/artists/show.html.erb
<h4>This is the Artist Show Page</h4>


<p> 
<strong>Artist:</strong> <%= @artist.name %>
</p>

<p> 
<strong>Bio:</strong> <%= @artist.bio %>
</p>

<%= button_to "Back 2 Featured Artist", artists_path, method: :get%>
<br>
<%= button_to "Edit #{@artist.appos} Info", edit_artist_path(@artist), method: :get%>
<%= button_to "Delete #{@artist.name}", @artist, method: :delete %>

<h4>Disctography</h4>
<% @artist.songs.each do |s| %>
<%= link_to "#{s.name}", song_path(s.id) %>

<% end %>

app/views/genres/index.html.erb
<h5>This is the List of Genres</h5>


<% @genres.each do |g| %>
<ul>
    <li>
    
    <%= g.name %>

    </li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeatsByRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<h5>Songs on File </h5>

<ul>
<% @songs.each do |s| %>
   
   <li>"<%= s.name %>" By: <%= s.artist.name %> </li> 
<% end %>
</ul>

app/views/songs/new.html.erb
<h3>Create a New Song!</h3>

<%= form_for(@song) do |f| %>

<%= f.label :New_Song %>
<%= f.text_field :name %>
<%= f.collection_select :genre_id, Genre.all, :id , :name  %>
<%= f.collection_select :artist_id, Artist.all, :id , :name  %>
<%= f.submit "Sing it!!" %>
<% end %>
  